site_name: Technical Documentation
theme:
  name: material
  custom_dir: docs/assets/overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: flaredark
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: logo.svg                # Put it in the overrides folder!
  favicon: assets/favicon.png
  features:
    - navigation.tabs           # Top-level pages are shown as tabs on the header
    - navigation.tabs.sticky    # Navigation tabs are always visible
    - navigation.top            # "Back to top" button appears upon upward scrolling
    - navigation.indexes        # Allow section headers to have a page (see tech/index.md)
    - content.tabs.link
markdown_extensions:
  - admonition                  # Info boxes (in different colors)
  - pymdownx.details            # "
  - pymdownx.superfences        # Info boxes, tabs
  - pymdownx.caret              # Allow superscript and insertion marks (^ and ^^)
  - pymdownx.tilde              # Allow subscript and deletion marks (~ and ~~)
  - pymdownx.keys               # Allow Keyboard marks (++)
  - pymdownx.mark               # Allow selection marks (==)
  - pymdownx.inlinehilite       # Syntax-highlight inline code
  - pymdownx.tabbed:            # Tabbed content
      alternate_style: true
  - toc:                        # TOC control
      permalink: "#"            # Add permalinks to headers
  - pymdownx.arithmatex:        # Math blocks
      generic: true
  - attr_list                   # { Annotations }
  - md_in_html                  # Markdown inside HTML
  - def_list                    # Definition lists (Glossary)
  - pymdownx.snippets           # Import files with --8<--
plugins:
  - search                      # Search box at the top
  - git-revision-date           # Last edit timestamp at the bottom
  - autolinks                   # Use just filenames instead of full or relative paths
  - redirects:                  # Allow creating redirects for moved pages
      redirect_maps:
          'en/state-connector.md':  'tech/state-connector.md'
          'technology/glossary.md': 'tech/glossary.md'
          'technology/state-connector.md': 'tech/state-connector.md'
          'networks/songbird.md': 'dev/reference/network-config.md'
          'networks/coston-testnet.md': 'dev/reference/network-config.md'
          'tech/flare-launch-process.md': 'tech/archive/flare-launch-process.md'
          'tutorials/wallets/index.md': 'user/wallets/index.md'
          'tutorials/wallets/bifrost-wallet.md': 'user/wallets/bifrost-wallet.md'
          'tutorials/wallets/dcent-wallet.md': 'user/wallets/dcent-wallet.md'
          'tutorials/wallets/how-to-access-flare-network-with-a-ledger-device.md': 'user/wallets/how-to-access-flare-network-with-a-ledger-device.md'
          'tutorials/wallets/how-to-access-flare-network-with-a-trezor-device.md': 'user/wallets/how-to-access-flare-network-with-a-trezor-device.md'
          'tutorials/wallets/how-to-access-flare-network-with-metamask.md': 'user/wallets/how-to-access-flare-network-with-metamask.md'
          'tutorials/wallets/safepal-s1-wallet.md': 'user/wallets/safepal-s1-wallet.md'
          'tutorials/wallets/brave-wallet.md': 'user/wallets/brave-wallet.md'
          'tutorials/explorer/songbird-explorer.md': 'user/block-explorers/index.md'
          'tutorials/explorer/coston-explorer.md': 'user/block-explorers/index.md'
          'tutorials/developing-on-top-of-flare/README.md': 'dev/index.md'
          'tutorials/developing-on-top-of-flare/important-links.md': 'dev/index.md'
          'tutorials/delegation/README.md': 'user/delegation/index.md'
          'tutorials/delegation/delegation-in-detail.md': 'tech/ftso.md'
          'tutorials/delegation-faq/README.md': 'tech/ftso.md'
          'tutorials/delegation-faq/block-explorer-+-metamask.md': 'user/delegation/managing-delegations.md'
          'tutorials/reward-claiming/README.md': 'tech/ftso.md'
          'tutorials/reward-claiming/reward-claiming-in-detail.md': 'user/delegation/managing-rewards.md'
          'tutorials/reward-faq/README.md': 'tech/ftso.md'
          'tutorials/reward-faq/block-explorer-+-metamask.md': 'user/delegation/managing-rewards.md'
          'tutorials/price-provider/setting-up-an-observation-node/README.md': 'infra/observation/deploying.md'
          'tutorials/price-provider/setting-up-an-observation-node/observation-node-faq.md': 'infra/observation/deploying.md'
          'tutorials/price-provider/ftso-price-provider/README.md': 'infra/data/operating.md'
          'tutorials/price-provider/ftso-price-provider/price-provider-faq.md': 'infra/data/operating.md'
          'tutorials/price-provider/ftso-price-provider/whitelisting-a-price-provider.md': 'infra/data/whitelisting.md'
          'tutorials/price-provider/ftso-price-provider/whitelisting-price-provider-faq.md': 'infra/data/whitelisting.md'
          'tutorials/price-provider/troubleshooting/price-provider.md': 'infra/data/operating.md'
          'infra/data/deploying.md':  'infra/data/operating.md'
          'tutorials/price-provider/troubleshooting/observation-node.md': 'infra/observation/deploying.md'
          'tutorials/price-provider/whitelisting.md': 'infra/data/whitelisting.md'
          'dev/reference/flare.md': 'dev/reference/network-config.md'
          'dev/reference/songbird.md': 'dev/reference/network-config.md'
          'dev/reference/coston-testnet.md': 'dev/reference/network-config.md'
          'dev/reference/network-configs.md': 'dev/reference/network-config.md'
          'dev/contracts.md': 'dev/getting-started/contract-addresses.md'
          'user/delegation/delegation-overview.md': 'tech/ftso.md'
          'user/delegation/delegation-faq.md': 'tech/ftso.md'
          'user/delegation/delegation-in-detail.md': 'tech/ftso.md'
          'user/delegation/manual-delegation.md': 'user/delegation/managing-delegations.md'
          'user/delegation/manual-reward-claiming.md': 'user/delegation/managing-rewards.md'
          'user/delegation/reward-claiming.md': 'tech/ftso.md'
          'user/delegation/reward-claiming-faq.md': 'tech/ftso.md'
          'user/delegation/reward-claiming-in-detail.md': 'tech/ftso.md'

extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/mathjax.js
  - assets/javascripts/images.js
  - assets/javascripts/links.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  social:
    - icon: fontawesome/solid/house
      link: https://flare.network
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/FlareNetworks
    - icon: fontawesome/brands/github
      link: https://github.com/flare-foundation
    - icon: fontawesome/brands/discord
      link: https://discord.gg/XqNa7Rq
  analytics:
    provider: google
    property: G-3WZ2CSGYV1
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
copyright: >-
  &copy; 2023 Flare Networks. <a href="#__consent">Cookie settings</a>.
site_url: https://docs.flare.network
repo_url: https://github.com/flare-foundation/docs
edit_uri: edit/main/docs/
nav:
  - Home:
    - index.md
  - Flare Fundamentals:
    - tech/index.md
    - tech/flare.md
    - tech/automatic-claiming.md
    - tech/the-flaredrop.md
    - tech/flare-beta.md
    - tech/api-portal.md
    - tech/ftso.md
    - tech/governance.md
    - tech/personal-delegation-account.md
    - tech/state-connector.md
    - tech/validators.md
    - tech/glossary.md
    - Archive:
      - tech/archive/index.md
      - tech/archive/flare-launch-process.md
  - User Guides:
    - user/index.md
    - user/automatic-claiming.md
    - Block Explorers:
      - user/block-explorers/index.md
      - user/block-explorers/finding-reward-epoch.md
      - Managing Delegations: user/block-explorers/managing-delegations.md
      - Managing Rewards: user/block-explorers/managing-rewards.md
      - user/block-explorers/verifying-vote-power-block.md
      - user/block-explorers/viewing-nfts.md
      - user/block-explorers/viewing-token-balances.md
      - user/block-explorers/viewing-token-transfers.md
      - user/block-explorers/viewing-transactions.md
      - user/block-explorers/user-interface.md
    - user/claiming-the-flaredrop.md
    - FTSO Delegation:
      - user/delegation/index.md
      - Managing Delegations: user/delegation/managing-delegations.md
      - Managing Rewards: user/delegation/managing-rewards.md
    - Governance:
      - user/governance/index.md
      - user/governance/voting.md
    - user/personal-delegation-account.md
    - Wallets:
      - user/wallets/index.md
      - user/wallets/bifrost-wallet.md
      - user/wallets/brave-wallet.md
      - user/wallets/dcent-wallet.md
      - user/wallets/enkrypt-wallet.md
      - user/wallets/how-to-access-flare-network-with-a-ledger-device.md
      - user/wallets/how-to-access-flare-network-with-metamask.md
      - user/wallets/safepal-s1-wallet.md
      - user/wallets/how-to-access-flare-network-with-a-trezor-device.md
    - user/wrapping-tokens.md
  - Infrastructure Guides:
    - infra/index.md
    - Attestation Providers:
      - infra/attestation/index.md
      - infra/attestation/operating.md
    - FTSO Data Providers:
      - infra/data/index.md
      - infra/data/operating.md
      - infra/data/whitelisting.md
      - Managing the Ecosystem:
        - infra/data/managing-ecosystem/index.md
        - infra/data/managing-ecosystem/exploring-collusion.md
        - infra/data/managing-ecosystem/monitoring-price-history.md
    - Observer Nodes:
      - infra/observation/index.md
      - infra/observation/deploying.md
      - infra/observation/faq.md
    - Validator Nodes:
      - infra/validation/index.md
      - infra/validation/deploying.md
  - Exchange Guides:
    - exchange/index.md
    - exchange/architecture.md
    - exchange/delegation.md
    - exchange/troubleshooting.md
  - Developer Docs:
    - dev/index.md
    - Getting Started:
      - dev/getting-started/index.md
      - Setting Up Your Environment:
        - dev/getting-started/setup/index.md
        - Using Remix: dev/getting-started/setup/remix.md
        - Using Hardhat: dev/getting-started/setup/hardhat.md
        - Using Truffle: dev/getting-started/setup/truffle.md
        - Using Foundry: dev/getting-started/setup/foundry.md
      - dev/getting-started/contract-addresses.md
    - Tutorials:
      - dev/tutorials/index.md
      - Accessing the Network:
        - dev/tutorials/network-access/index.md
        - dev/tutorials/network-access/transaction-finalization.md
        - dev/tutorials/network-access/reliable-event-reading.md
        - dev/tutorials/network-access/obtaining-revert-reason.md
    - Reference Guides:
      - dev/reference/index.md
      - dev/reference/network-config.md
      - dev/reference/automatic-claiming.md
      - dev/reference/explorers-and-indexers.md
      - dev/reference/the-flaredrop.md
      - dev/reference/personal-delegation-account.md
      - dev/reference/wallets.md
    - dev/external-resources.md
    - dev/tools.md
  - APIs:
    - apis/index.md